spring:
   application:
     name: weweibuy-backstage
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
     url: jdbc:mysql://localhost:3306/small01             # 数据库名称
     username: root
     password: root
     dbcp2:
       min-idle: 5                                           # 数据库连接池的最小维持连接数
       initial-size: 5                                       # 初始化连接数
       max-total: 5                                          # 最大连接数
       max-wait-millis: 200

server:
  port: 8001

##配置日志
                #logging:
                #  #配置日志文件路径
                #  file: log
                #  level:
                #    root: debug


logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    instance:
        instance-id: weweibuy-backstage
        prefer-ip-address: true     #访问路径可以显示IP地址

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weiwei.po    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


feign:
  hystrix:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

