server:
  port: 8001

spring:
   profiles:
     active: @profileActive@
   application:
     name: webuy-backstage
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
     url: jdbc:mysql://47.99.129.104:3306/small01?useUnicode=true&characterEncoding=UTF-8             # 数据库名称
     username: user01
     password: ak402507979
     initialSize: 5
     minIdle: 5
     maxActive: 20
     maxWait: 60000
     poolPreparedStatements: true           # 打开PSCache，并且指定每个连接上PSCache的大小
     maxPoolPreparedStatementPerConnectionSize: 20
     filters: stat,wall,logback    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     connectionProperties:
        druid:
          stat:
            mergeSql: true   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            slowSqlMillis: 5000
   cache:
      type: redis
      redis:
        time-to-live: 200000  #缓存超时时间ms
        cache-null-values: false  #是否缓存空值
   redis:
     database: 0 # Redis数据库索引（默认为0）
     host: 47.99.129.104  #Redis服务器地址
     port: 6379 # Redis服务器连接端口
     password: ak402507979 # Redis服务器连接密码（默认为空）
     jedis:
       max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
       max-idle: 3 # 连接池中的最大空闲连接
       max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
       min-idle: 2 # 连接池中的最小空闲连接
       timeout: 2000 # 连接超时时间（毫秒）

#  boot:
#    admin:
#      url: http://localhost:8001/application/admin




logging:
  config: classpath:config/logback/logback-spring.xml

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:ak402507979@47.99.129.104:7001/eureka
  instance:
    instance-id: webuy-backstage
    prefer-ip-address: true     #访问路径可以显示IP地址
    ip-address: 47.99.129.104
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
    lease-expiration-duration-in-seconds: 30  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
                                              #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
                                              #默认90s
    lease-renewal-interval-in-seconds: 10   #服务刷新时间配置，每隔这个时间会主动心跳一次
                                           #默认30s
mybatis:
  config-location: classpath:config/mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuy.po    # 所有Entity别名类所在包
  mapper-locations: classpath:config/mybatis/mapper/**/*.xml                       # mapper映射文件

ribbon:
  ReadTimeout: 4000  #请求处理的超时时间
  ConnectTimeout: 3000 #请求连接的超时时间
  ServerListRefreshInterval: 5000  #eureka客户端ribbon刷新时间,默认30s


feign:
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 2000   #请求处理的超时时间
        readTimeout: 12000  #请求连接的超时时间
  hystrix:
    enabled: false  #是否启用feign的 hystrix
  compression: #Spring Cloud Feign支持对请求和响应进行GZIP压缩，以提高通信效率
      request:
        enabled:  true   # 开启对 request 请求压缩
        mime-types:
          - text/xml
          - application/xml
          - application/json    # 指定压缩格式
        min-request-size: 2048  # 压缩的最小阀值，默认 2048，超过2048 （字节） 进行压缩。

      response:
        enabled:  true  # 开启对 response 的压缩

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false #是否启动Hystrix的超时 如果enabled设置为false，则请求超时交给ribbon控制
        isolation:
          thread:
            timeoutInMilliseconds: 2000


