spring:
   application:
     name: weweibuy-search
   datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
        url: jdbc:mysql://localhost:3306/small01             # 数据库名称
        username: root
        password: root
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        poolPreparedStatements: true           # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,logback    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        connectionProperties:
           druid:
             stat:
               mergeSql: true   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
               slowSqlMillis: 5000
#     dbcp2:
#       min-idle: 5                                           # 数据库连接池的最小维持连接数
#       initial-size: 5                                       # 初始化连接数
#       max-total: 5                                          # 最大连接数
#       max-wait-millis: 200

server:
  port: 8101

##配置日志
                #logging:
                #  #配置日志文件路径
                #  file: log
                #  level:
                #    root: debug


logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    instance:
        instance-id: weweibuy-backstage
        prefer-ip-address: true     #访问路径可以显示IP地址

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.weweibuyuy.po    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


feign:
  hystrix:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

