spring:
  application:
    name: learning-activity
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/learning-activiti?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
    username: user01
    password: ak402507979
    hikari:
      register-mbeans: true
  activiti:
    database-schema-update: true
    # 开启历史库
    db-history-used: true
    history-level: audit
#    check-process-definitions: false